"""add foreighn keys

Revision ID: 0532b75f5def
Revises: 1ce1e186aa61
Create Date: 2023-03-31 20:05:55.273947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0532b75f5def'
down_revision = '1ce1e186aa61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
