"""current updates

Revision ID: 1321bb2f0b98
Revises: dc99cdd13e56
Create Date: 2023-09-01 11:03:43.698607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1321bb2f0b98'
down_revision = 'dc99cdd13e56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
