"""add foreighn keys

Revision ID: 22a96622de99
Revises: ad9d8b10dd28
Create Date: 2023-03-31 13:17:26.024693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22a96622de99'
down_revision = 'ad9d8b10dd28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countryFlag',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('country', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('picture', postgresql.BYTEA(), nullable=True),
    sa.Column('begins', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_countryFlag_code'), 'countryFlag', ['code'], unique=False)
    op.create_table('language',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('iso2', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('begins', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_language_iso2'), 'language', ['iso2'], unique=True)
    op.create_index(op.f('ix_language_name'), 'language', ['name'], unique=False)
    op.create_table('translation',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('table', sa.String(), nullable=True),
    sa.Column('object', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('language', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('begins', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['language'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('translation_idx', 'translation', ['table', 'object', 'language'], unique=False)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=False)
    op.add_column('currency', sa.Column('name_plural', sa.String(), nullable=True))
    op.add_column('currency', sa.Column('symbol', sa.String(), nullable=True))
    op.add_column('currency', sa.Column('decimal_digits', sa.Integer(), nullable=True))
    op.add_column('currency', sa.Column('rounding', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'rounding')
    op.drop_column('currency', 'decimal_digits')
    op.drop_column('currency', 'symbol')
    op.drop_column('currency', 'name_plural')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index('translation_idx', table_name='translation')
    op.drop_table('translation')
    op.drop_index(op.f('ix_language_name'), table_name='language')
    op.drop_index(op.f('ix_language_iso2'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_countryFlag_code'), table_name='countryFlag')
    op.drop_table('countryFlag')
    # ### end Alembic commands ###
