"""add foreighn keys

Revision ID: 248cc7b65264
Revises: d478f0140968
Create Date: 2023-03-31 20:09:15.797963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248cc7b65264'
down_revision = 'd478f0140968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
