"""current updates

Revision ID: 50066e9125cd
Revises: 5d2cd2ce4b19
Create Date: 2023-04-06 23:45:18.299025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50066e9125cd'
down_revision = '5d2cd2ce4b19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
