"""current updates

Revision ID: 5d2cd2ce4b19
Revises: 64f73e8aa4eb
Create Date: 2023-04-03 10:53:29.414707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d2cd2ce4b19'
down_revision = '64f73e8aa4eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'category',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('currency', 'iso',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('currency_idx', table_name='currency')
    op.create_index('currency_idx', 'currency', ['category', 'iso'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currency_idx', table_name='currency')
    op.create_index('currency_idx', 'currency', ['category', 'iso_num'], unique=False)
    op.alter_column('currency', 'iso',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('currency', 'category',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
