"""add foreighn keys

Revision ID: 895f22da6afc
Revises: dcecf5e6672a
Create Date: 2023-04-02 17:49:06.317731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895f22da6afc'
down_revision = 'dcecf5e6672a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
