"""add foreighn keys

Revision ID: ad9d8b10dd28
Revises: 9aea61ffcac1
Create Date: 2023-03-27 23:49:15.208456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9d8b10dd28'
down_revision = '9aea61ffcac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('iso2', sa.String(), nullable=True))
    op.add_column('country', sa.Column('iso3', sa.String(), nullable=True))
    op.add_column('country', sa.Column('m49', sa.String(), nullable=True))
    op.drop_index('ix_country_code', table_name='country')
    op.create_index(op.f('ix_country_iso2'), 'country', ['iso2'], unique=True)
    op.create_index(op.f('ix_country_iso3'), 'country', ['iso3'], unique=True)
    op.create_index(op.f('ix_country_m49'), 'country', ['m49'], unique=True)
    op.drop_column('country', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_country_m49'), table_name='country')
    op.drop_index(op.f('ix_country_iso3'), table_name='country')
    op.drop_index(op.f('ix_country_iso2'), table_name='country')
    op.create_index('ix_country_code', 'country', ['code'], unique=False)
    op.drop_column('country', 'm49')
    op.drop_column('country', 'iso3')
    op.drop_column('country', 'iso2')
    # ### end Alembic commands ###
