"""current updates

Revision ID: aeada104a8ae
Revises: 50066e9125cd
Create Date: 2023-08-23 16:06:18.890552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aeada104a8ae'
down_revision = '50066e9125cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('country_currency_fkey', 'country', type_='foreignkey')
    op.drop_column('country', 'currency')
    op.drop_index('state_idx', table_name='state')
    op.create_index('state_idx', 'state', ['category', 'code', 'state'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('state_idx', table_name='state')
    op.create_index('state_idx', 'state', ['category', 'code'], unique=False)
    op.add_column('country', sa.Column('currency', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('country_currency_fkey', 'country', 'currency', ['currency'], ['id'])
    # ### end Alembic commands ###
