"""current updates

Revision ID: dc99cdd13e56
Revises: aeada104a8ae
Create Date: 2023-09-01 00:24:01.974725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc99cdd13e56'
down_revision = 'aeada104a8ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currency_idx', table_name='currency')
    op.create_index('currency_idx', 'currency', ['category', 'iso_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currency_idx', table_name='currency')
    op.create_index('currency_idx', 'currency', ['category', 'iso'], unique=False)
    # ### end Alembic commands ###
