"""add foreighn keys

Revision ID: dcecf5e6672a
Revises: 248cc7b65264
Create Date: 2023-03-31 21:59:32.886931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcecf5e6672a'
down_revision = '248cc7b65264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'numcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_currency_numcode'), 'currency', ['numcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_numcode'), table_name='currency')
    op.alter_column('currency', 'numcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
