"""alchemy20

Revision ID: dfbfda3ccbc0
Revises: 1985b3b9acc3
Create Date: 2024-02-06 09:39:41.663231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbfda3ccbc0'
down_revision = '1985b3b9acc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
