"""current updates

Revision ID: e424fd0694bc
Revises: 766ef6e6e136
Create Date: 2023-09-22 16:18:35.996779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e424fd0694bc'
down_revision = '766ef6e6e136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('table', sa.String(), nullable=True),
    sa.Column('category', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('object', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('begins', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('access_idx', 'access', ['table', 'category', 'code'], unique=False)
    op.create_index(op.f('ix_access_code'), 'access', ['code'], unique=False)
    op.create_index(op.f('ix_access_object'), 'access', ['object'], unique=False)
    op.create_index(op.f('ix_access_table'), 'access', ['table'], unique=False)
    op.drop_index('currency_idx', table_name='currency')
    op.create_index('currency_idx', 'currency', ['category', 'code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currency_idx', table_name='currency')
    op.create_index('currency_idx', 'currency', ['category', 'num'], unique=False)
    op.drop_index(op.f('ix_access_table'), table_name='access')
    op.drop_index(op.f('ix_access_object'), table_name='access')
    op.drop_index(op.f('ix_access_code'), table_name='access')
    op.drop_index('access_idx', table_name='access')
    op.drop_table('access')
    # ### end Alembic commands ###
